### ISSUE TITLE
remove `:repo` field

### ISSUE THREAD

**Issue by uvtc** [goto-engineering/powered-by-janet#3]
In an individual project's own page, it may make sense to remove the ":repo" field. In gitter, I asked about it and @bakpakin replied:

> > uvtc wrote:
> > In a project.janet, what does the "git+https" in ":repo "git+https://github.com/.../..." mean?
>
> bakpakin wrote:
> The some of the metadata in project.janet is not actually used for anything. I had planned to use 
> that metadata but it turned out not to be useful
> 
> The :repo key can be ignored as an argument to declare-project
>
> It was just a convention to indicate the preferred source control and repository for a project
>
> > Ok. Thanks. Will use :url with a value of its git repo url.

**Comment by goto-engineering** [comment]
Thx I'll take it out.

**Comment by goto-engineering** [comment]
Done
